name: My GitHub CI/CD Demo
on:
  push:
    tags:
      - v*
      - '!*alpha*'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Say somthing
        run: echo Hello Action

